### ISSUE TITLE
Crash right clicking a mimic chest

### ISSUE THREAD

**Issue by SaadArdati** [Lyinginbedmon/VariousOddities#3]
`    at com.lying.variousoddities.tileentity.TileEntityMimicChest.func_73660_a(TileEntityMimicChest.java:288)
    at net.minecraft.world.World.func_72939_s(World.java:1835)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by Lyinginbedmon** [comment]
Which version did this occur in? Could you post the full crash log?

**Comment by SaadArdati** [comment]
`varodd-1.12.2-4.0.jar`

**Comment by Lyinginbedmon** [comment]
This is a known bug in version 4.0, it was fixed in September

https://www.curseforge.com/minecraft/mc-mods/various-oddities/issues/15
